// <auto-generated />
using GalgjeGame.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GalgjeGame.Migrations
{
    [DbContext(typeof(GalgjeContext))]
    [Migration("20220426124344_AddedLinkBetweenTwoUserClasses")]
    partial class AddedLinkBetweenTwoUserClasses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GalgjeGame.DomainClasses.UserGameScore", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"), 1L, 1);

                    b.Property<int>("IncorrectGuesses")
                        .HasColumnType("int");

                    b.Property<int>("TimeElapsedInGuessing")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("UserName");

                    b.ToTable("UserGameScores");
                });

            modelBuilder.Entity("GalgjeGame.DomainClasses.UserOverallScore", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TimesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("WordsGuessed")
                        .HasColumnType("int");

                    b.HasKey("UserName");

                    b.ToTable("UserOverallScores");
                });

            modelBuilder.Entity("GalgjeGame.Words", b =>
                {
                    b.Property<string>("Word")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Word");

                    b.ToTable("WordsToBeGuessed");
                });

            modelBuilder.Entity("GalgjeGame.DomainClasses.UserGameScore", b =>
                {
                    b.HasOne("GalgjeGame.DomainClasses.UserOverallScore", "userOverallScore")
                        .WithMany("userGameScores")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userOverallScore");
                });

            modelBuilder.Entity("GalgjeGame.DomainClasses.UserOverallScore", b =>
                {
                    b.Navigation("userGameScores");
                });
#pragma warning restore 612, 618
        }
    }
}
