// <auto-generated />
using GalgjeGame.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GalgjeGame.Migrations
{
    [DbContext(typeof(GalgjeContext))]
    [Migration("20220426122137_InitialCreateV2")]
    partial class InitialCreateV2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GalgjeGame.DomainClasses.UserGameScore", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"), 1L, 1);

                    b.Property<int>("IncorrectGuesses")
                        .HasColumnType("int");

                    b.Property<int>("TimeElapsedInGuessing")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("UserGameScores");
                });

            modelBuilder.Entity("GalgjeGame.DomainClasses.UserOverallScore", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"), 1L, 1);

                    b.Property<int>("TimesPlayed")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordsGuessed")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("UserOverallScores");
                });

            modelBuilder.Entity("GalgjeGame.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"), 1L, 1);

                    b.Property<long>("UserGameID")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("UserScoreID")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.HasIndex("UserGameID");

                    b.HasIndex("UserScoreID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GalgjeGame.Words", b =>
                {
                    b.Property<string>("Word")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Word");

                    b.ToTable("WordsToBeGuessed");
                });

            modelBuilder.Entity("GalgjeGame.User", b =>
                {
                    b.HasOne("GalgjeGame.DomainClasses.UserGameScore", "UserGame")
                        .WithMany()
                        .HasForeignKey("UserGameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalgjeGame.DomainClasses.UserOverallScore", "UserScore")
                        .WithMany()
                        .HasForeignKey("UserScoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserGame");

                    b.Navigation("UserScore");
                });
#pragma warning restore 612, 618
        }
    }
}
